name: assa_abloy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  shared_preferences: ^2.2.2

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
